cleanup a little more of the GHAs for Mac

diff --git a/.github/workflows/BookShelvesMac-CI-Main.yml b/.github/workflows/BookShelvesMac-CI-Main.yml
--- a/.github/workflows/BookShelvesMac-CI-Main.yml
+++ b/.github/workflows/BookShelvesMac-CI-Main.yml
@@ -30,15 +30,28 @@ on:
     branches: 
       - '**'
 
-env:
-  CSPROJ: 'src/BookShelves.Maui/BookShelves.Maui.csproj'
-  PUBLISH_PATH: '${{ github.workspace }}/publish-output'
-  MAC_ARTIFACTS_PATH: 'artifacts_mac'
-  BUILD_LOG_FILE: 'mac.binlog'
+concurrency:
+  group: maui-mac-main-${{github.ref}}
+  cancel-in-progress: true
 
 jobs:
   mac-build-mac:
     runs-on: macos-15
+    timeout-minutes: 45
+    env:
+      CSPROJ: 'src/BookShelves.Maui/BookShelves.Maui.csproj'
+      PUBLISH_PATH: '${{ github.workspace }}/publish-output'
+      MAC_ARTIFACTS_PATH: 'artifacts_mac'
+      BUILD_LOG_FILE: 'mac.binlog'
+      BUNDLE_ID: 'com.azmoore.bookshelves.maui'
+      CODESIGN_PROVISION: 'BookShelves MacOS Provisioning'
+      CODESIGN_KEY: 'Apple Distribution: Derek Moore (TPKXH5FT2P)'
+      PACKAGE_SIGNING_KEY: '3rd Party Mac Developer Installer: Derek Moore (TPKXH5FT2P)'
+      CODESIGN_ENTITLEMENTS: 'Platforms\MacCatalyst\Entitlements.plist'
+      DOTNET_VERSION: 'net9.0'
+      DOTNET_SDK_VERSION: '9.0.x'
+      RELEASE_CONFIGURATION: 'Release'
+      XCODE_VERSION: '16.4'
 
     steps:
       - uses: actions/checkout@v4
@@ -52,16 +65,20 @@ jobs:
             echo Currently selected Xcode:
             xcrun xcode-select --print-path
 
-      - name: Select Xcode 16.4
-        run: sudo xcode-select -s /Applications/Xcode_16.4.app #/Contents/Developer
+      # Select your required version
+      - name: Select Xcode ${{env.XCODE_VERSION}}
+        run: sudo xcode-select -s /Applications/Xcode_${{env.XCODE_VERSION}}.app #/Contents/Developer
 
-      - name: xcode diags 2
-        run: |
-            echo Currently selected Xcode:
-            xcrun xcode-select --print-path
+      - name: Verify Xcode version
+        run: xcodebuild -version
+
+      # - name: xcode diags 2
+      #   run: |
+      #       echo Currently selected Xcode:
+      #       xcrun xcode-select --print-path
 
       - name: Add Xcode developer tools to PATH
-        run: export PATH="/Applications/Xcode_16.4.app/Contents/Developer/usr/bin:$PATH"
+        run: export PATH="/Applications/Xcode_${{env.XCODE_VERSION}}.app/Contents/Developer/usr/bin:$PATH"
 
       - name: Set some env variables (CURRENT_DATE, CURRENT_TIME, ASSEMBLY_BUILD_NUMBER)
         run: |
@@ -101,24 +118,27 @@ jobs:
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: 9.0.x
+          dotnet-version: ${{env.DOTNET_SDK_VERSION}}
           # include-prerelease: true
 
       # - name: Add msbuild to PATH
       #   uses: microsoft/setup-msbuild@v2
 
-      - name: Install MAUI Workloads
-        run: |
-          dotnet workload install maui --source https://api.nuget.org/v3/index.json
+      - name: Restore Workloads
+        run: dotnet workload restore ${{env.CSPROJ}}
+
+      # - name: Install MAUI Workloads
+      #   run: |
+      #     dotnet workload install maui --source https://api.nuget.org/v3/index.json
 
       - name: Cert Info 1
         env:
-          CERTIFICATE_BASE64: ${{ secrets.MAC_COMBINED_DIST_INST_CERT_P12 }}
+          CERTIFICATE_BASE64: ${{secrets.MAC_COMBINED_DIST_INST_CERT_P12}}
         run: |
           echo $CERTIFICATE_BASE64 | base64 --decode > cert.p12
       - name: Cert Info 2
         run: |
-          openssl pkcs12 -in cert.p12 -passin pass:${{ secrets.IOS_DIST_CERTIFICATES_P12_PASSWORD }} -info -nokeys
+          openssl pkcs12 -in cert.p12 -passin pass:${{secrets.IOS_DIST_CERTIFICATES_P12_PASSWORD}} -info -nokeys
 
       - name: Import Code-Signing Certificates
         uses: Apple-Actions/import-codesign-certs@v5
@@ -126,12 +146,12 @@ jobs:
           # p12-file-base64: ${{ secrets.IOS_ALL_PLATFORM_DIST_CERTIFICATES_P12 }}
 
           # use this one for Mac app store/test flight
-          p12-file-base64: ${{ secrets.MAC_COMBINED_DIST_INST_CERT_P12 }}
+          p12-file-base64: ${{secrets.MAC_COMBINED_DIST_INST_CERT_P12}}
           
           # use this one for ad-hoc
           #p12-file-base64: ${{ secrets.APPLE_DEVELOPMENT_CERT_P12 }}
           
-          p12-password: ${{ secrets.IOS_DIST_CERTIFICATES_P12_PASSWORD }}
+          p12-password: ${{secrets.IOS_DIST_CERTIFICATES_P12_PASSWORD}}
       
       # - name: Import Installer-Signing Certificates
       #   uses: Apple-Actions/import-codesign-certs@v1
@@ -154,38 +174,38 @@ jobs:
       - name: Download Apple Provisioning Profiles
         uses: Apple-Actions/download-provisioning-profiles@v4
         with:
-          bundle-id: 'com.azmoore.bookshelves.maui'
+          bundle-id: ${{env.BUNDLE_ID}}
           # profile-type: 'MAC_APP_DEVELOPMENT' (get all profiles)
-          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.APPLE_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.APPLE_APPSTORE_PRIVATE_KEY }}
+          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
+          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
+          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}
 
       - name: Download Apple Provisioning Profiles
         uses: Apple-Actions/download-provisioning-profiles@v4
         with:
-          bundle-id: 'com.azmoore.bookshelves.maui'
+          bundle-id: ${{env.BUNDLE_ID}}
           profile-type: 'MAC_APP_DEVELOPMENT'
-          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.APPLE_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.APPLE_APPSTORE_PRIVATE_KEY }}
+          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
+          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
+          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}
 
       - name: Download Apple Provisioning Profiles
         uses: Apple-Actions/download-provisioning-profiles@v4
         with:
-          bundle-id: 'com.azmoore.bookshelves.maui'
+          bundle-id: ${{env.BUNDLE_ID}}
           profile-type: 'MAC_CATALYST_APP_DEVELOPMENT'
-          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.APPLE_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.APPLE_APPSTORE_PRIVATE_KEY }}
+          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
+          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
+          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}
 
       - name: Download Apple Provisioning Profiles
         uses: Apple-Actions/download-provisioning-profiles@v4
         with:
-          bundle-id: 'com.azmoore.bookshelves.maui'
+          bundle-id: ${{env.BUNDLE_ID}}
           profile-type: 'MAC_APP_STORE'
-          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.APPLE_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.APPLE_APPSTORE_PRIVATE_KEY }}
+          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
+          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
+          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}
 
       - name: Rename file 
         run: |
@@ -217,8 +237,11 @@ jobs:
       - name: Create publish folder
         shell: pwsh
         run: |
-          cd ${{ github.workspace }}
-          mkdir -p ${{ env.PUBLISH_PATH }}
+          cd ${{github.workspace}}
+          mkdir -p ${{env.PUBLISH_PATH}}
+
+      - name: NuGet Restore
+        run: dotnet restore ${{env.CSPROJ}}
 
       - name: Build MAUI Mobile app
         shell: pwsh
@@ -229,22 +252,39 @@ jobs:
           #dotnet publish ${{env.CSPROJ}} -v diag -bl:${{env.BUILD_LOG_FILE}} -f net8.0-maccatalyst -c Release -o ${{ env.PUBLISH_PATH }} -p:ApplicationVersion=${{ env.ASSEMBLY_BUILD_NUMBER }} -p:MtouchLink=SdkOnly -p:CreatePackage=true -p:EnableCodeSigning=true -p:CodesignKey="Apple Development: Derek Moore (C52LX4JJTM)" -p:CodesignProvision="BookShelvesApp (MacCatalyst Ad-Hoc)" -p:UseHardenedRuntime=true
 
           #app store deployment   -p:RuntimeIdentifier=maccatalyst-x64
-          dotnet publish ${{env.CSPROJ}} -v normal -bl:${{env.BUILD_LOG_FILE}} -f net9.0-maccatalyst -c Release -o ${{ env.PUBLISH_PATH }} -p:ApplicationVersion=${{ env.ASSEMBLY_BUILD_NUMBER }} -p:MtouchLink=SdkOnly -p:CreatePackage=true -p:EnableCodeSigning=true -p:CodesignKey="Apple Distribution: Derek Moore (TPKXH5FT2P)" -p:CodesignProvision="BookShelves MacOS Provisioning" -p:EnablePackageSigning=true -p:PackageSigningKey="3rd Party Mac Developer Installer: Derek Moore (TPKXH5FT2P)" -p:CodesignEntitlements="Platforms\MacCatalyst\Entitlements.plist" -p:UseHardenedRuntime=true
+          dotnet `
+            publish `
+            ${{env.CSPROJ}} `
+            -f ${{env.DOTNET_VERSION}}-maccatalyst `
+            -c ${{env.RELEASE_CONFIGURATION}} `
+            -o ${{env.PUBLISH_PATH}} `
+            -p:ApplicationVersion=${{env.ASSEMBLY_BUILD_NUMBER}} `
+            -p:MtouchLink=SdkOnly `
+            -p:CreatePackage=true `
+            -p:EnableCodeSigning=true `
+            -p:CodesignKey="${{env.CODESIGN_KEY}}" `
+            -p:CodesignProvision="${{env.CODESIGN_PROVISION}}" `
+            -p:EnablePackageSigning=true `
+            -p:PackageSigningKey="${{env.PACKAGE_SIGNING_KEY}}" `
+            -p:CodesignEntitlements="${{env.CODESIGN_ENTITLEMENTS}}" `
+            -p:UseHardenedRuntime=true
+            # -v normal `
+            # -bl:${{env.BUILD_LOG_FILE}} `
 
           #--self-contained false -p:RuntimeIdentifierOverride=android-x64 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}"
           #dotnet publish ${{env.CSPROJ}} -bl:mobile.binlog -c Release -r win10-x64 -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None
       
-      - name: Show publish folder content
+      - name: Show workspace folder content
         shell: pwsh
         run: |
-          cd '${{ github.workspace }}'
-          Get-Childitem -Path ${{ github.workspace }} -Include *.* -File -Recurse
+          cd '${{github.workspace}}'
+          Get-Childitem -Path ${{github.workspace}} -Include *.* -File -Recurse
           # Get-Childitem -Path ${{ github.workspace }} -Include *.plist -File -Recurse
 
       - name: Show publish folder content
         shell: pwsh
         run: |
-          Get-Childitem -Path ${{ env.PUBLISH_PATH }} -Include *.* -File -Recurse
+          Get-Childitem -Path ${{env.PUBLISH_PATH}} -Include *.* -File -Recurse
 
       # - name: version
       #   run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
@@ -268,40 +308,53 @@ jobs:
       #     # Write-Host "APPLICATION_DISPLAY_VERSION=${{ steps.get_application_version.outputs.APPLICATION_DISPLAY_VERSION }}"
       #     Write-Host "APPLICATION_DISPLAY_VERSION=$($env:APPLICATION_DISPLAY_VERSION)"
 
+      - name: Locate PKG
+        # if: ${{ github.event_name == 'workflow_dispatch' }}
+        id: findpkg
+        run: |
+          PKG_PATH=$(find ${{env.PUBLISH_PATH}} -maxdepth 1 -name '*.pkg' | head -n1)
+          # IPA_PATH=$(find MyScoreBoardMaui/bin/${{env.RELEASE_CONFIGURATION}}/${{env.DOTNET_VERSION}}-ios/${{env.RUNTIME_ID}}/publish -maxdepth 1 -name '*.ipa' | head -n1)
+          if [ -z "$PKG_PATH" ]; then
+            echo 'PKG not found' >&2
+            exit 1
+          fi
+          echo "pkg=$PKG_PATH" >> $GITHUB_OUTPUT
+
       - name: 'Upload app to TestFlight'
         uses: apple-actions/upload-testflight-build@v3
         with:
           app-type: osx
           # app-path: '${{ env.PUBLISH_PATH }}/BookShelves.Maui-0.1.2.pkg' 
-          app-path: '${{ env.PUBLISH_PATH }}/BookShelves.Maui-${{ env.APPLICATION_DISPLAY_VERSION }}.pkg'
-          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.APPLE_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.APPLE_APPSTORE_PRIVATE_KEY }}
+          # app-path: '${{env.PUBLISH_PATH }}/BookShelves.Maui-${{ env.APPLICATION_DISPLAY_VERSION }}.pkg'
+          app-path: ${{steps.findpkg.outputs.pkg}}
+          issuer-id: ${{secrets.APPLE_APPSTORE_ISSUER_ID}}
+          api-key-id: ${{secrets.APPLE_APPSTORE_KEY_ID}}
+          api-private-key: ${{secrets.APPLE_APPSTORE_PRIVATE_KEY}}
         if: github.event_name == 'pull_request' || github.event_name == 'push'
 
-      - name: Archive build log
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: logs
-          path: '${{env.BUILD_LOG_FILE}}'
+      # - name: Archive build log
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: logs
+      #     path: '${{env.BUILD_LOG_FILE}}'
 
-      - name: Create artifacts folder
-        shell: pwsh
-        run: |
-          cd ${{ github.workspace }}
-          mkdir -p ${{ env.MAC_ARTIFACTS_PATH }}
+      # - name: Create artifacts folder
+      #   shell: pwsh
+      #   run: |
+      #     cd ${{ github.workspace }}
+      #     mkdir -p ${{ env.MAC_ARTIFACTS_PATH }}
 
-      - name: Copy Mac PKG package
-        shell: pwsh
-        run: |
-          Get-Childitem -Path ${{ github.workspace }} -Include *BookShelves*.pkg -File -Recurse | Copy-Item -Destination ${{ env.MAC_ARTIFACTS_PATH }}
+      # - name: Copy Mac PKG package
+      #   shell: pwsh
+      #   run: |
+      #     Get-Childitem -Path ${{ github.workspace }} -Include *BookShelves*.pkg -File -Recurse | Copy-Item -Destination ${{ env.MAC_ARTIFACTS_PATH }}
       
       - name: Archive build artifact
         uses: actions/upload-artifact@v4
         with:
           name: 'mac pkg'
-          path: ${{ env.MAC_ARTIFACTS_PATH }} #'${{ github.workspace }}/src/BookShelves.WinUI/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/*'
+          path: ${{steps.findpkg.outputs.pkg}} #${{ env.MAC_ARTIFACTS_PATH }} #'${{ github.workspace }}/src/BookShelves.WinUI/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/*'
           compression-level: 0
 
       # # BUILD
